#pragma once

typedef enum {
    TEXTURE_PACOPEN,
    TEXTURE_PACCLOSED,
    TEXTURE_GHOST,
    TEXTURE_DEAD_GHOST,

    TEXTURE_ERROR
} texture_index_t;

enum {
    SOUND_PACMAN_CHOMP,
    SOUND_PACMAN_DEATH,
    SOUND_PACMAN_EATFRUIT,
    SOUND_PACMAN_EATGHOST,
    SOUND_PACMAN_EXTRAPAC,
    SOUND_PACMAN_INTERMISSION
};